version: "3.9"

services:
  node_app:
    container_name: node_app
    build: .
    image: faoziyarisma/node_employee_app
    ports:
      - "3000:3000"
    environment:
      - PG_HOST=node_employee_db
      - PG_USER=faoziyarisma
      - PG_PASSWORD=july28R)
      - PG_HOST=node_db
    depends_on:
      - node_db
    restart: always

  node_db:
    container_name: node_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=node_employee_db
      - POSTGRES_USER=faoziyarisma
      - POSTGRES_PASSWORD=july28R)
    volumes:
      - node_db_data:/var/lib/postgresql/data

volumes:
  node_db_data: {}
  
    
